var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                            *                                                                     ",
   "                                                                                                                !!",
   "         *                      *                                                                            !!!!!",
   "                                                                      o o o                             xxxxx!xxxx",
   "                *                                                  o o o o o o                    xxxxxxxx!!!xxxxx",
   "                                    *                               o o o o o                xxxxxxxxxxxxxxxxxxxxx",
   "        *                                                             o o o               xxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                   o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          *       *                     o o  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    *                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxx!!!!!!xxxxxx!xxxxxxxxxxxxxxxxxxxxxxx",
   "                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!     !!      !!xxxxxxxxxxxxxxxxxxxxxxxx",
   "    *                        o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxx  !               !xx!!xxxxxxxxxxxxxxxxxxxx",
   "                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!                       xxx!xxxxxxxxxxxxxxxxxx",
   "                        o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!                            !!!xxxxxxxxxxxxxxxxxx",
   "                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!                              ! xxxxxxxxxxxxxxxxx",
   "                    oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                      !xxxxxxxxxxxxxxx",
   "                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                         xxxxxxxxxxxxxx",
   "xx            xxxxxxxxxxxxxxxxxxxxxx                                                                 xxxxxxxxxxxxx",
   "xx @         xxxx                         o   o                                                       xxxxxxxxxxxx",
   "xxxx                   o             o            o                                                      xxxxxxxxx",
   "!!!Xxx                     o    o          #                      oo         #           o o o        o  xxxxxxxxx",
   "!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxx  xx  xxxxxxx xx   xxxxxxx    xxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                ",
   "                    *                                           !!!!       *    ",
   "                                      *           *             !xx!            ",
   "      *                                                        !xxxxx!       *  ",
   "                  *                      *                    !xxxxxxx!         ",
   "                                *                            !xxxxxxxxx         ",
   "           *             !!                                 xxxxxxxxxxxx        ",
   "                        !!!!                *             !xxxxxxxxxxxxxxx!     ",
   "       *               !xxxx!                             xxxxxxxxxxxxxxxxxx    ",
   "                     !xxxxxx!                          xxxxxxxxxxxxxxxxxxxxx!!!!",
   "                     !xxxxxxxx!                      xxxxxxxxxxxxxxxxxxxxxxxxx!!",
   "                    xxxxxxxxxxx                     xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "          *         xxxxxxxxxxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                 !xxxxxxxxxxxxxxxxx                                 xxxxxxxxxxxx",
   "  *             xxxxxxxxxxxxxxxxxxxxx                                xxxxxxxxxxx",
   "             !!xxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxx o o o o xxxxxxxx",
   "            xxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxx  o o o xxxxxxx",
   "           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ooo xxxxxxx",
   "       !!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxx!!xxxxxx ooo  xxxxxxx",
   "      !xxxxxxxxxxxxxxxxxxxxxxxxxx!x!!!!!!!!!!!!!!!!!!!!!!! xxx!!!xx  ooo xxxxxxx",
   "!!!!!xxxxxxxxxxxxxxxx!!xxxxxx!xxx!#    !!       !#     !    !!x!xxxxxxxxxxxxxxxx",
   "!!!xxxxxxxxxxxxxxxxxxxxx!x!! !!!!!                              !!!xx!xxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxx!x!!#        !                                !!#   !!xxxxxxx",
   "xxxxxxxxxxxxxxx !!  #!                                                  #! xxxxx",
   "xxxxxxxxxxx!!#                                                               !xx",
   "xxxxxxx                                                                      xxx",
   "xxxxx                                                                         xx",
   "xxx                                                                           xx",
   "xxx   @                 o      o o     o      #       o                o      xx",
   "xxxxxxxxxxxxxxxxxxxx    xx    xxxxx   xxxx   xxxx    xxx   xx    xx   xxx     xx",
   "xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     xx",
   "xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     xx",
   "xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     xx",
   "xxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx     xx",
   "xxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xx",
   "xxxxxx                           xxxxxxxxxxxxxxxx            xxxxxxx          xx",
   "xxxxx                               xxxxxxxxxx      o o o      xxx          xxxx",
   "xxxxx             o o o               xxxx                                xxxxxx",
   "xxxxx          xxxxxxxxxxxx                        xxxxxxxxx           xxxx!xxxx",
   "xxxxx      xxxxxxxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxx     xxxxxxx!!xx",
   "xxxxx    xxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxx                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxx",
   "xxxxx                                         xxxxxxxxxxxxxxxxx               xx",
   "xxxxx                                         xxxxxxxxxxxxxxx                 xx",
   "xxxxx                                                    xxx                  xx",
   "xxxxx                                                   xx                    xx",
   "xxxxx                                                  xx      xxxxxxxxx      xx",
   "xxxxx                                                  xx   pp    xx    x    xxx",
   "xxxxx                                                   xxx pp xxx      x     xx",
   "xxxxx                                                     xxxxxx        x     xx",
   "xxxxx                                                                   xxxx  xx",
   "xxxxx        o                                                          x     xx",
   "xxxxx                      o                         o o                     xxx",
   "xxxxxxxxx                o   o                     o      o                   xx",
   "xxxxx                                                                         xx",
   "xxxxx         xx              xx  o                                  xxxxxxxxxxx",
   "xxxxx         xx    xxxxxxx   xx  xx  xxxxx    xxxxxxx ## xxxxxxx             xx",
   "xxxxx!!!!!!!!!xx!!!!!xxxxx!!!!xx!!xx!!xxxxx!!!!!!xxxxx!!!!xxxx!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!x!!!!!!!xxx!!!!!x!!!!x!!!xxx!!!!!!!!!xxx!!!!xxx!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!x!!!!!!!!!!!!xx!!xx!!!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "          *          *                                                                                   ",
   "            *       *                        *                       *                                   ",
   "            *       *         *              *     *                 *                                   ",
   "            *      *           *             *                      *                                    ",
   "            *      *            *            *          *  **       *                                    ",
   "             *    *             *     *     *      *    * *  *      *                                    ",
   "              * *               *   *   *  *       *    *    *      *                                    ",
   "                                 *      *  *       *   *    *                                            ",
   "                                  *      *        *    *    *       **                                   ",
   "                                                                    *                                    ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                     !!!!!!!!            ",
   "                                                                                 !!!!!!!!!!!!!!!         ",
   "                                                                               !!!!!!!!!!!!!!!!!!!!      ",
   "                  !!!!!!!                                                      !!xxxxxxxxxxxxxxx!!!      ",
   "               !!!!!!!!!!!!!                                                  xxxxxxxxxxxxxxxxxxxxxxx    ",
   "              !!xxxxxxxxxxx!!                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "           xxxxxxxxxxxxxxxxxxxxx               xxxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                         ",
   "                                                                                                         "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
